name: "Front: Lint and Format Validation"

on:
  push:
    paths:
      - 'front/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container:
      image: node:20-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and run linter
        working-directory: front
        run: |
          npm install
          npm run lint
